[connections.default]
warehouse = "CICD_WH"
role = "ACCOUNTADMIN"
database = "CICD_DEMO_DB"
schema = "TECH"
account = "${SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT}"
user = "${SNOWFLAKE_CONNECTIONS_DEFAULT_USER}"
authenticator = "SNOWFLAKE_JWT"
private_key_file = ".snowflake/rsa_key.pem"
password = "Singh007@mr@it"